apiVersion: v1
kind: Service
metadata:
  name: grandstack-kit-prod-client
  labels:
    app: grandstack-kit
    environment: prod
    component: client
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: grandstack-kit
    environment: prod
    component: client
    tier: frontend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grandstack-kit-prod-client
  labels:
    app: grandstack-kit
    environment: prod
    component: client
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grandstack-kit
      environment: prod
      component: client
      tier: frontend
  template:
    metadata:
      labels:
        app: grandstack-kit
        environment: prod
        component: client
        tier: frontend
    spec:
      containers:
        - name: grandstack-kit-client
          image: registry.digitalocean.com/grandstack-kit/client:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]
