apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: me@domain.com # replace with your email
    privateKeySecretRef:
      name: letsencrypt-staging
    # use whichever solver your platform provides https://cert-manager.io/docs/configuration/acme/dns01/
    solvers:
      - dns01:
          digitalocean:
            tokenSecretRef:
              name: digitalocean-dns
              key: access-token
